version: 0.1.6.{build}
image: Visual Studio 2022
environment:
  matrix:
    - GENERATOR: '"Visual Studio 17 2022" -A x64'
      BUILD_TYPE: Release
      BUILD_SHARED: 'ON'
      FATAL_ERRORS: 'ON'
      WCHAR: 'ON'
      WCHAR_FILES: 'ON'
      BUILD_EXAMPLE: 'OFF'
      USE_STD_FORMAT: 'ON'
      CXX_STANDARD: 17
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
build_script:
  - cmd: >-
      set

      mkdir build

      cd build

      cmake -G %GENERATOR% ..
      
      cmake --build . --config %BUILD_TYPE%